apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 7
  selector:
    matchLabels:
      potato: squirrel
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        potato: squirrel
    spec:
      containers:
        - name: nginx-container
          image: nginx
